### PR TITLE
Add support for composer

### PR DESCRIPTION
**Pull request by ablagoev**
Add support for Composer (Dependency Manager for PHP).

### CODE REVIEW

**Comment by drslump** [comment]
thanks!

**Comment by dlsniper** [comment]
@drslump you need to submit your package to Packagist so that it's properly listed there. Currently there's only a fork of it: https://packagist.org/packages/rgooding/protobuf-php

Cheers.

**Comment by drslump** [comment]
@dlsniper Thanks for pointing that out, however I guess that if @rgooding wants to maintain the package in **packagist.org** he is free to do so and less work for me :sunglasses:

**Comment by HunterXuan** [comment]
Hi, could you please submit this package to Packagist?

**Pull request merged**
